[pytest]
addopts = -s -v
python_files = *_tests.py test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: mark for smoke tests
    unit: mark for module tests
    integration: mark for integration tests
    api: mark for api tests
    e2e: mark for e2e tests
    auth: mark for auth tests
    category: mark for category resourse tests
    user: mark for user resourse tests
    article: mark for article resourse tests
    file: mark for file resourse tests