spring.application.name=aiworkshop
spring.web.resources.add-mappings=false

spring.datasource.url=jdbc:postgresql://localhost:5432/ai-workshop
spring.datasource.name=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

server.servlet.context-path=/api

jwt.secret=lajfiuhfligahdfashgfsgjsdljgajsgkusagvuvagvjhifghuaygcac
jwt.expirationMs=86400000