"""Update category table

Revision ID: 1f9c0083ab8f
Revises: f4f45c7cf721
Create Date: 2025-06-11 00:02:50.466727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f9c0083ab8f"
down_revision: Union[str, None] = "f4f45c7cf721"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("article_category_article_id_fkey"), "article_category", type_="foreignkey")
    op.create_foreign_key(None, "article_category", "articles", ["article_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "article_category", type_="foreignkey")
    op.create_foreign_key(
        op.f("article_category_article_id_fkey"), "article_category", "articles", ["article_id"], ["id"]
    )
    # ### end Alembic commands ###
