"""Replace relationship between files and articles

Revision ID: 26b9a7650278
Revises: c110639c4e7a
Create Date: 2025-07-19 17:54:51.961111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26b9a7650278"
down_revision: Union[str, None] = "c110639c4e7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_to_file",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "file_id"),
        sa.UniqueConstraint("file_id", name="uq_file_article"),
    )
    op.drop_constraint(op.f("files_article_id_fkey"), "files", type_="foreignkey")
    op.drop_column("files", "article_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("article_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("files_article_id_fkey"), "files", "articles", ["article_id"], ["id"])
    op.drop_table("article_to_file")
    # ### end Alembic commands ###
