"""Add category cascade, article_id cascade and categoru_id cascade in article_category

Revision ID: 71e44bc25879
Revises: 26b9a7650278
Create Date: 2025-07-22 19:17:38.038871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71e44bc25879"
down_revision: Union[str, None] = "26b9a7650278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("article_category_category_id_fkey"), "article_category", type_="foreignkey")
    op.create_foreign_key(None, "article_category", "categorys", ["category_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("article_to_file_article_id_fkey"), "article_to_file", type_="foreignkey")
    op.drop_constraint(op.f("article_to_file_file_id_fkey"), "article_to_file", type_="foreignkey")
    op.create_foreign_key(None, "article_to_file", "articles", ["article_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "article_to_file", "files", ["file_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "article_to_file", type_="foreignkey")
    op.drop_constraint(None, "article_to_file", type_="foreignkey")
    op.create_foreign_key(op.f("article_to_file_file_id_fkey"), "article_to_file", "files", ["file_id"], ["id"])
    op.create_foreign_key(
        op.f("article_to_file_article_id_fkey"), "article_to_file", "articles", ["article_id"], ["id"]
    )
    op.drop_constraint(None, "article_category", type_="foreignkey")
    op.create_foreign_key(
        op.f("article_category_category_id_fkey"), "article_category", "categorys", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###
