"""Add username and delete image_url for users

Revision ID: c110639c4e7a
Revises: 1f9c0083ab8f
Create Date: 2025-07-18 18:53:53.671353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c110639c4e7a"
down_revision: Union[str, None] = "1f9c0083ab8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=False))
    op.drop_column("users", "image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("users", "username")
    # ### end Alembic commands ###
